### ISSUE TITLE
Passing options into the .srt() call.

### ISSUE THREAD

**Issue by Mement0o** [jbarrow/srt-player#1]
Hello! 
I cant figure out how to pass options into the .srt() call.

I tried things like:
  $("audio").srt(srt_track: "url");

I am a beginner in Jquery sorry, I would appreciate any help this is really the plugin I was looking for for my project!

Thank you 

Guilhem

**Comment by jbarrow** [comment]
Sorry for the delay! If this is still useful:

The url setting is passed in by using the `srt-track` attribute on the `<video>` element. So, for instance:

```
<video ... srt-track="{url}">
```

Then have jQuery initialize the `video` element with the `srt-player`:

```
<script type="text/javascript">
  $("video").srt();
</script>
```
